# 1. Read Image and convert image colour


In [1]:
import cv2

In [2]:
!pip install opencv-python

In [3]:
!pip install opencv-contrib-python


In [4]:
img = cv2.imread("C:\\Users\\VIHAL\\OneDrive\\Desktop\\Images\\child.jpg")

In [5]:
img

array([[[  1, 109, 191],
        [  1, 109, 191],
        [  1, 109, 191],
        ...,
        [  2, 108, 191],
        [  1, 108, 189],
        [  0, 108, 189]],

       [[  1, 109, 191],
        [  1, 109, 191],
        [  1, 109, 191],
        ...,
        [  2, 108, 191],
        [  0, 108, 189],
        [  0, 108, 189]],

       [[  1, 109, 191],
        [  1, 109, 191],
        [  1, 109, 191],
        ...,
        [  2, 108, 191],
        [  0, 108, 189],
        [  0, 108, 189]],

       ...,

       [[  1, 102, 181],
        [  2, 103, 182],
        [  2, 103, 182],
        ...,
        [  2, 103, 182],
        [  2, 103, 182],
        [  2, 103, 182]],

       [[  0, 103, 182],
        [  0, 103, 182],
        [  0, 103, 182],
        ...,
        [  2, 103, 182],
        [  1, 102, 181],
        [  1, 102, 181]],

       [[  0, 103, 182],
        [  0, 103, 182],
        [  0, 103, 182],
        ...,
        [  2, 103, 182],
        [  1, 102, 181],
        [  1, 102, 181]]

In [6]:
#1. Convert RBG image to gray scale
cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

array([[121, 121, 121, ..., 121, 120, 120],
       [121, 121, 121, ..., 121, 120, 120],
       [121, 121, 121, ..., 121, 120, 120],
       ...,
       [114, 115, 115, ..., 115, 115, 115],
       [115, 115, 115, ..., 115, 114, 114],
       [115, 115, 115, ..., 115, 114, 114]], dtype=uint8)

In [7]:
# convert BGR format to Grayscale
img_g = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)


In [8]:
cv2.imshow('frame1', img)
cv2.imshow('frame2', img_g)

# press any key with 0 wait time
cv2.waitKey(0)
# Close all imageframe
cv2.destroyAllWindows()

# 2. Edge Detection using canny filter in OpenCV

In [9]:
import cv2

img = cv2.imread("C:\\Users\\VIHAL\\OneDrive\\Desktop\\Images\\parrot.jpg")

cv2.imshow('Original', img)
# convert BGR format to Grayscale
img_g = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Canny(image, threshold1, threshold2)
# Computing Edge Gradient with canny thresholds
# The edge gradients that are greater tha threshold value will be detected as Edges
# thresholds lower than threshold1 will not be considered as edges.
edges_low = cv2.Canny(img_g, 50, 120)
cv2.imshow('Edge Detection', edges_low)

edges_high = cv2.Canny(img_g, 60, 200)
cv2.imshow('High Edge Detection', edges_high)



In [10]:
# press any key with 0 wait time
cv2.waitKey(0)
# Close all imageframe
cv2.destroyAllWindows()

# 3. Smoothning of Image
# Different ways of smothning - usung Filter 2D, Average, Median, Gaussian

In [12]:
# Apply smoothening of Image - Apply Blur
import cv2 
import numpy as np

img = cv2.imread("C:\\Users\\VIHAL\\OneDrive\\Desktop\\Images\\avengers.png")

# Blur using Filter2D
kernel = np.ones((5,5), np.float32) / 25
print(kernel)

# Filter2D
smoothed = cv2.filter2D(img, -1, kernel)

# Average Blur
img_blur = cv2.blur(img, (5,5))

# Median Blur
m_blur = cv2.medianBlur(img, 7)

# Gaussian Blur, sigmaX(stdDev)= 1
g_blur = cv2.GaussianBlur(img, (7,7), 1)

cv2.imshow('Original', img)
cv2.imshow('Blur', smoothed)
cv2.imshow('average', img_blur)
cv2.imshow('median', m_blur)
cv2.imshow('gaussian', g_blur)

# press any key with 0 wait time
cv2.waitKey(0)
# Close all imageframe
cv2.destroyAllWindows()

[[0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]]
