In [1]:
# Apply smoothening of Image - Apply Blur
import cv2 
import numpy as np


In [2]:
img = cv2.imread("C:\\Users\\VIHAL\\OneDrive\\Desktop\\Images\\avengers.png")


In [3]:
# Blur using Filter2D
kernel = np.ones((5,5), np.float32) / 25
print(kernel)

[[0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]
 [0.04 0.04 0.04 0.04 0.04]]


In [4]:
# Filter2D
smoothed = cv2.filter2D(img, -1, kernel)

In [5]:
# Average Blur
img_blur = cv2.blur(img, (5,5))

In [6]:
# Median Blur
m_blur = cv2.medianBlur(img, 7)

In [7]:
# Gaussian Blur, sigmaX(stdDev)= 1
g_blur = cv2.GaussianBlur(img, (7,7), 1)

In [8]:
cv2.imshow('Original', img)
cv2.imshow('Blur', smoothed)
cv2.imshow('average', img_blur)
cv2.imshow('median', m_blur)
cv2.imshow('gaussian', g_blur)

In [9]:
# press any key with 0 wait time
cv2.waitKey(0)

27

In [10]:
# Close all imageframe
cv2.destroyAllWindows()