In [1]:
import cv2
import random

def noise_black_white(image):
    # Get the dimensions of Image
    row, col = image.shape
    num_of_pixels = random.randint(1500, 20000)
    for i in range(num_of_pixels):
        # pick random y-coordinate
        y_coordinate = random.randint(0, row - 1)
        # pick random x-coordinate
        x_coordinate = random.randint(0, col - 1)
        image[y_coordinate][x_coordinate] = 255     # 255 = for white
    for i in range(num_of_pixels):
        # pick random y-coordinate
        y_coordinate = random.randint(0, row - 1)   # 0 = for black
        #0 is colour code for black
        # pick random x-coordinate
        x_coordinate = random.randint(0, col - 1)
        image[y_coordinate][x_coordinate] = 0
    return image

image = cv2.imread("C:\\Users\\VIHAL\\OneDrive\\Desktop\\Images\\parrot.jpg", cv2.IMREAD_GRAYSCALE)

cv2.imshow('Original Image', image)
cv2.imshow('Noisy Image',noise_black_white(image))

cv2.imwrite("C:\\Users\\VIHAL\\OneDrive\\Desktop\\Images\\noisy-image.jpg",noise_black_white(image))

# press any key with 0 wait time
cv2.waitKey(0)
# Close all imageframe
cv2.destroyAllWindows()

In [2]:
# import cv2
# def salt_and_paper(image):
#     for 
# image = cv2.imread("C:/Users/VIHAL/Desktop/A/parrot.jpg")

# \

# Processing noisy image

In [3]:
import numpy as np
img = cv2.imread("C:\\Users\\VIHAL\\OneDrive\\Desktop\\Images\\noisy-image.jpg")

# Blur using Filter2D
kernel = np.ones((3,3), np.float32) / 9
print(kernel)

# Filter2D
smoothed = cv2.filter2D(img, -1, kernel)

# Average Blur
img_blur = cv2.blur(img, (5,5))

# Median Blur
m_blur = cv2.medianBlur(img, 7)

# Gaussian Blur, sigmaX(stdDev)= 1
g_blur = cv2.GaussianBlur(img, (7,7), 1)

cv2.imshow('Original', img)
cv2.imshow('Blur', smoothed)
cv2.imshow('average', img_blur)
cv2.imshow('median', m_blur)
cv2.imshow('gaussian', g_blur)

# press any key with 0 wait time
cv2.waitKey(0)
# Close all imageframe
cv2.destroyAllWindows()

[[0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]
 [0.11111111 0.11111111 0.11111111]]
